Add GasPriceChecker deamon
bitzlato/belomor pull request #21
Opened 2022-03-24 11:22 UTC by huryv45

2022-03-25 11:30 UTC, radanisk requested changes
Выглядит норм 👍 Ещё бы добавить API для получения blockchains, чтоб фронт мог начать ходить за ними в беломор вместо Peatio

2022-03-25 11:33 UTC, radanisk approved these changes

2022-03-28 09:31 UTC, huryv45 commented on config/blockchains.yml
> +  eth-mainnet:
@radanisk взял эти значения с peatio, они валидные?

2022-03-28 11:31 UTC, radanisk commented on config/blockchains.yml
> +  eth-mainnet:
@huryv45 да

2022-03-30 07:54 UTC, merged