[#181152422] get listtransactions data from database
bitzlato/belomor pull request #8
Opened 2022-02-22 09:28 UTC by huryv45

2022-02-24 13:18 UTC, radanisk requested changes

2022-02-24 13:18 UTC, radanisk commented on app/models/imports/legacy_transactions.rb
> +          break
Мы в этот if попадаем? В каком случае?

2022-02-24 13:18 UTC, radanisk commented on app/operations/node_operations/base_operation.rb
> +      node_response['result']
Мож накинем базовую обработку некорректных ответов от ноды? Например, если она будет постоянно возвращать пустой результат, то мы похоже это можем далеко не сразу заметить?

2022-02-24 13:18 UTC, radanisk commented on db/migrate/20220217125641_create_legacy_transactions.rb
> +    add_index :legacy_transactions, :txid, unique: true
Насколько понимаю, уникальность txid в рамках разных сетей ничем не гарантируется. Не правильнее ли здесь использовать уникальность по паре txid+blockchain_id?

2022-02-24 19:13 UTC, huryv45 commented on app/operations/node_operations/listtransactions.rb
> +        .offset(offset)
все верно, сейчас максимальный оффсет в 10к, но в реальности похоже в ответе записей сильно меньше

2022-02-24 19:14 UTC, huryv45 commented on db/migrate/20220217125641_create_legacy_transactions.rb
> +    add_index :legacy_transactions, :txid, unique: true
согласен, переделаю

2022-02-24 19:15 UTC, huryv45 commented on app/operations/node_operations/base_operation.rb
> +      node_response['result']
ты имеешь ввиду кидать сообщения в лог?

2022-02-24 19:18 UTC, huryv45 commented on app/models/imports/legacy_transactions.rb
> +          break
1) мы пошли за списком транзакций, за 5 минут их может накопиться много
2) мы ходим пачками по 100 штук и пытаемся заимпортить их
3) если получаем ошибку с уникальностью ключа txid - в какой-то из пачек, то это значит, что еще за следующими 100 транзакциями ходить не нужно, а нужно из последней 100 загрузить те, которых нет в базе
4) выходим из цикла, так как больше новых транзакций там нет

2022-02-24 19:20 UTC, huryv45 commented on config/schedule.rb
> +  rake 'import:legacy_transactions'
давай

2022-02-25 07:02 UTC, huryv45 commented on config/schedule.rb
> +  rake 'import:legacy_transactions'
посмотрел, с ним кажется как-то все сложнее поднимается, отдельный `MultiService` еще, думаю с кроном проще и надежнее

2022-02-25 07:13 UTC, radanisk commented on app/operations/node_operations/base_operation.rb
> +      node_response['result']
Да, как вариант, на твоё усмотрение. Мож и об уведомлениях в багснег, просто не до конца понимаю возможные варианты ответов ендпоинта.

2022-02-25 07:13 UTC, huryv45 commented on app/operations/node_operations/base_operation.rb
> +      node_response['result']
тут согласен, сделаю

2022-02-25 13:17 UTC, huryv45 commented on app/operations/node_operations/base_operation.rb
> +      node_response['result']
накинул метрику в prometheus

2022-03-05 08:26 UTC, radanisk approved these changes

2022-03-09 08:02 UTC, closed without merging